### ISSUE TITLE
Won't work if there is no system rbenv command installed

### ISSUE THREAD

**Issue by dmeranda** [SchemaPlus/schema_dev#10]
In ruby_selector's Rbenv class it removes all `.rbenv` directories out of the `$PATH` and other environment variable cleansing.  However, if there is no global system-installed `rbenv` command, then this means that it can no longer find any rbenv command to run `rbenv versions --bare`

```
$ schema_dev bundle install
...
/home/.../.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema_dev-3.5.1/lib/schema_dev/ruby_selector.rb:41:in ``': No such file or directory - rbenv (Errno::ENOENT)
	from /home/.../.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema_dev-3.5.1/lib/schema_dev/ruby_selector.rb:41:in `initialize'
	from /home/.../.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema_dev-3.5.1/lib/schema_dev/ruby_selector.rb:8:in `new'
	from /home/.../.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/schema_dev-3.5.1/lib/schema_dev/ruby_selector.rb:8:in `command'
...
```

The user-installed rbenv is:
```
$ which rbenv
~/.rbenv/bin/rbenv

$ rbenv --version
rbenv 0.4.0-190-gc30e096

$ rbenv versions --bare
1.9.3-p484
2.2.3
```

**Comment by ronen** [comment]
Drat.  It used to work for me with rbenv.  Yeah I probably had rbenv installed in /usr/local via homebrew.  Unfortunately I don't use rbenv any more (I use chruby now), so it'll be hard for me to debug.   

Looks like it'd be possible to reorder the code so that it runs `rbenv versions --bare` before it cleanses the environment...   would you be willing to try it and make a PR?

**Comment by dmeranda** [comment]
I verified that moving the assignment of `@versions` to the top of `Rbenv.initialize` seems to work, at least with some limited testing.  However I'm not sure what the purpose of altering the `$PATH` environment variable is.  I understand changing the other environment variables, but not the path.

Rather than moving the line that determines the available ruby versions, would it not work just as well to delete the line that filters out the `$PATH` variable?  Or perhaps only removing `.rbenv/shims` but not `.rbenv/bin`?

**Comment by ronen** [comment]
> However I'm not sure what the purpose of altering the $PATH environment variable is. I understand changing the other environment variables, but not the path.

> Rather than moving the line that determines the available ruby versions, would it not work just as well to delete the line that filters out the $PATH variable? Or perhaps only removing .rbenv/shims but not .rbenv/bin?

You're probably right.  I can't think of any reason that `$PATH` would need to be cleansed, if its contents don't depend on the version of ruby that were chosen.   I don't remember whether I included it in the cleansing because of a specific problem or just for thoroughness.  I *do* vaguely remember having some sort of problem which prompted me to do that cleansing in the first place, but I don't remember the details.   I should have added a more detailed comment at the time.

Anyway, since you use rbenv and I don't, I'd say feel free to make whatever changes you think best-- and once you've convinced yourself it really works I'll be happy to take your word for it and merge a PR.  (And if other people then raise rbenv-related issues, I might send them your way :)
